import Head from 'next/head';
import React from 'react';
import Navbar from '@/components/profile/navbar';
import ProfileInfo from '@/components/ProfileInfo';


const Profile = () => {
  return (
    <>
    <Head>

        <title>Mi Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />

    </Head>

  {/*---------------------BARRA DE NAVEGACION------------------------*/}
       <Navbar />
  {/*----------------------------------------------------------------*/}

     <ProfileInfo />
  
    </>
  );
};

export default Profile;
